# ruff: noqa

from __future__ import annotations

"""Compatibility re-export for the original monolithic server module."""

from opentalking.server.__main__ import main
from opentalking.server.broadcast import (
    CMD_GENERATE,
    CMD_INIT,
    CMD_NONE,
    CMD_SHUTDOWN,
    RANK,
    WORLD_SIZE,
    _init_bcast_device,
    _reset_audio_embedding_shape_cache,
    broadcast_audio_embedding,
    broadcast_cmd,
    broadcast_string,
)
from opentalking.server.idle_cache import (
    _advance_idle_cache_cursor,
    _apply_idle_region_constraints,
    _build_idle_audio_chunk,
    _build_idle_cache_key,
    _build_idle_eye_mask,
    _build_idle_mouth_mask,
    _build_idle_refresh_audio_array,
    _crossfade_frames,
    _generate_idle_cache_frames,
    _generate_idle_cache_frames_local,
    _idle_cache_path,
    _load_idle_cache_frames,
    _load_reference_frame,
    _make_idle_cache_key,
    _prepare_audio_embedding_for_chunk,
    _prepare_pipeline_state,
    _preload_idle_cache_for_ref,
    _render_video_frames_for_audio_embedding,
    _render_video_frames_for_audio_embedding_local,
    _run_pipeline_for_audio_embedding,
    _run_session_warmup,
    _run_startup_warmup,
    _sample_idle_hold_chunks,
    _save_idle_cache_frames,
)
from opentalking.server.runtime import (
    AUDIO_CHUNK_BYTES,
    AUDIO_CHUNK_SAMPLES,
    AUDIO_END_IDX,
    AUDIO_START_IDX,
    CACHED_AUDIO_DURATION,
    CACHED_AUDIO_SAMPLES,
    DEFERRED_MOTION,
    FRAME_NUM,
    HEIGHT,
    IDLE_CACHE_CHUNKS,
    IDLE_CACHE_CROSSFADE_FRAMES,
    IDLE_CACHE_DIR,
    IDLE_CACHE_LEVEL,
    IDLE_CACHE_PLAYBACK,
    IDLE_CACHE_VERSION,
    IDLE_ENTER_CHUNKS,
    IDLE_EYE_LOCK,
    IDLE_EYE_TEMPORAL,
    IDLE_HOLD_MAX_CHUNKS,
    IDLE_HOLD_MIN_CHUNKS,
    IDLE_MOUTH_LOCK,
    IDLE_MOUTH_TEMPORAL,
    IDLE_PRELOAD_REFS,
    IDLE_RANDOM_SEED,
    IDLE_REFRESH_INTERVAL,
    IDLE_SILENCE_RMS,
    JPEG_QUALITY,
    JPEG_WORKERS,
    MOTION_FRAMES_NUM,
    PROGRESSIVE_SEND,
    SAMPLE_RATE,
    SLICE_LEN,
    STREAM_DECODE,
    TGT_FPS,
    WARMUP_ON_INIT,
    WARMUP_ON_STARTUP,
    WARMUP_PROMPT,
    WARMUP_REF_IMAGE,
    WARMUP_SEED,
    WIDTH,
    _append_audio_chunk,
    _chunk_rms,
    _command_file_path,
    _linearize_audio_buffer,
    _wait_for_command,
    _write_command,
)
from opentalking.server.video_codec import (
    MAGIC_AUDIO,
    MAGIC_VIDEO,
    _collect_jpeg_futures,
    _encode_jpeg_frame,
    _run_pipeline_deferred_for_audio_embedding,
    _run_pipeline_stream_for_audio_embedding,
    _run_stream_and_encode,
    _send_video_message,
    _submit_jpeg_futures,
    decode_jpeg_frame,
    encode_video_jpegs,
)
from opentalking.server.worker_loop import worker_loop
from opentalking.server.ws_server import ServerSession, _cleanup_temp_image, run_server
